Fix missing-prototypes
devperf.c:162:5: error: no previous prototype for 'DevPerfInit' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>